# Generated by Django 6.0.2 on 2026-02-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='specialists'),
        ),
    ]
