# Generated by Django 6.0.2 on 2026-02-11 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_service_service_description_specialist_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialist',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='specialists/'),
        ),
    ]
